# Generated by Django 4.0.6 on 2022-10-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_humanities_humanitiesquestions_mediacontents_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Humanities',
            new_name='Humanity',
        ),
        migrations.RenameModel(
            old_name='HumanitiesAnswers',
            new_name='HumanityAnswer',
        ),
        migrations.RenameModel(
            old_name='HumanitiesQuestions',
            new_name='HumanityQuestion',
        ),
        migrations.RenameModel(
            old_name='MediaContents',
            new_name='MediaContent',
        ),
        migrations.RenameModel(
            old_name='MediaContentsAnswers',
            new_name='MediaContentsAnswer',
        ),
        migrations.RenameModel(
            old_name='SocietyQuestions',
            new_name='MediaContentsQuestion',
        ),
        migrations.RenameModel(
            old_name='SocietyAnswers',
            new_name='SocietyAnswer',
        ),
        migrations.RenameModel(
            old_name='MediaContentsQuestions',
            new_name='SocietyQuestion',
        ),
    ]
