# Generated by Django 4.0.6 on 2022-10-11 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_humanities_humanity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontentsanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mediacontentsquestion'),
        ),
        migrations.AlterField(
            model_name='societyanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.societyquestion'),
        ),
    ]
