# Generated by Django 4.0.6 on 2022-10-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mediacontentsanswer_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Humanity_QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humanity_title', models.CharField(max_length=100)),
                ('humanity_body', models.TextField()),
                ('humanity_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IT_QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MediaContents_QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaContents_title', models.CharField(max_length=100)),
                ('mediaContents_body', models.TextField()),
                ('mediaContents_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Society_QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_title', models.CharField(max_length=100)),
                ('society_body', models.TextField()),
                ('society_name', models.CharField(max_length=10)),
            ],
        ),
    ]
